---
binary_sensor:
  - platform: template
    sensors:
      next_alarm:
        friendly_name: "Volgende Alarm"
        value_template: >-
          {{now().strftime("%a %h %d %H:%M %Z %Y") == (((state_attr('sensor.in2023_next_alarm', 'Time in Milliseconds')
          | int / 1000) + 0*60 ) | timestamp_custom('%a %h %d %H:%M %Z %Y'))}}
      update_available:
        friendly_name: "Update Available"
        value_template: "{{ (states('sensor.newest_dev_version') > states('sensor.installed_version')) }}"
