---
light:
  - platform: group
    name: Tuin
    entities:
      - light.patio
      - light.tuin_led
      - light.schuur
      - light.groot_licht
  - platform: group
    name: Woonkamer Spotjes
    entities:
      - light.woonkamer_spot_1
      - light.woonkamer_spot_2
  - platform: group
    name: Tuin Led
    entities:
      - light.tuin_led_1
      - light.tuin_led_2
      - light.tuin_led_3
      - light.tuin_led_4
  - platform: group
    name: Patio
    entities:
      - light.patio_led_1
      - light.patio_led_2
      - light.patio_led_3
      - light.patio_led_4
      - light.patio_led_5
      - light.patio_led_6
  - platform: group
    name: Zolder
    entities:
      - light.zolder_1
      - light.zolder_2
  - platform: group
    name: Schuur
    entities:
      - light.schuur_1
      - light.schuur_2
      - light.schuur_led
  - platform: group
    name: Alle Lichten
    entities:
      - light.gang
      - light.woonkamer_spot_1
      - light.woonkamer_spot_2
      - light.keuken
      - light.tuin
      - light.zolder
      - light.schuur
      - light.patio
      - light.slaapkamer
      - light.slaapkamer_elyza
      - light.kast
      - light.spotjes_santi
      - light.wc_licht
      - light.keuken_spotjes
      - light.groot_licht
  - platform: switch
    name: Kast
    entity_id: switch.kast
  - platform: switch
    name: WC Licht
    entity_id: switch.wc_licht
  - platform: switch
    name: Keuken Spotjes
    entity_id: switch.keuken_schakelaar
  - platform: switch
    name: Groot Licht
    entity_id: switch.groot_licht
  - platform: switch
    name: Spotjes Santi
    entity_id: switch.schakelaar_santi
