---
sensor:
  - platform: rest
    resource: https://version.home-assistant.io/dev.json
    name: Newest DEV Version
    value_template: '{{ value_json.homeassistant.default }}'
    scan_interval: 1800
  - platform: command_line
    name: Installed Version
    command: "cat /config/.HA_VERSION"
  - platform: command_line
    name: Unraid CPU Temp
    value_template: "{{ value | multiply(0.001) | round(1) }}"
    command: "cat /sys/devices/virtual/thermal/thermal_zone0/temp"
  - platform: p2000
    name: Tilburg
    radius: '10000'
    regios: '20'
  - platform: uptime
    name: Time Online
