---
template:
  - sensor:
      - name: "House Usage"
        unit_of_measurement: "Watt"
        state: "{{ states('sensor.power_consumption')|float * 1000 }}"
        device_class: energy
        state_class: measurement
        # last_reset: "1970-01-01T00:00:00+00:00"
        unique_id: 2222
