---
template:
  - sensor:
      - name: "House Usage"
        unit_of_measurement: "Watt"
        state: "{{ states('sensor.power_consumption') | replace('.','') | int * 10 }}"
        device_class: energy
        state_class: measurement
        unique_id: 2222
