---
utility_meter:
  uurlijks_verbruik_dal:
    source: sensor.energy_consumption_tarif_1
    cycle: hourly
  dagelijks_verbruik_dal:
    source: sensor.energy_consumption_tarif_1
    cycle: daily
  weekelijks_verbruik_dal:
    source: sensor.energy_consumption_tarif_1
    cycle: weekly
  maandelijks_verbruik_dal:
    source: sensor.energy_consumption_tarif_1
    cycle: monthly
  uurlijks_verbruik_normaal:
    source: sensor.energy_consumption_tarif_2
    cycle: hourly
  dagelijks_verbruik_normaal:
    source: sensor.energy_consumption_tarif_2
    cycle: daily
  weekelijks_verbruik_normaal:
    source: sensor.energy_consumption_tarif_2
    cycle: weekly
  maandelijks_verbruik_normaal:
    source: sensor.energy_consumption_tarif_2
    cycle: monthly
