- id: '1630828352706'
  alias: Schakelaar - Woonkamer
  description: ''
  use_blueprint:
    path: zha-ikea-tradfri-on-off.yaml
    input:
      remote: 174a5a7dde34839097574d90cae3b302
      button_on_short:
      - service: light.toggle
        target:
          device_id:
          - 3bb074ed31de730c605b417b20f23550
          - 46beae0f6a9e1d762da8bb079bf66eb9
      button_off_short:
      - type: toggle
        device_id: 4a825f490e0da8b7bab8474581891dd3
        entity_id: switch.kast
        domain: switch
      button_on_long:
      - device_id: 9e495e0b463a8a665dcb917e62658217
        domain: cover
        entity_id: cover.rolluik_achter
        type: set_position
      button_off_long:
      - device_id: 9e495e0b463a8a665dcb917e62658217
        domain: cover
        entity_id: cover.rolluik_achter
        type: set_position
        position: 100
- id: '1630828597105'
  alias: Schakelaar - Overloop
  description: ''
  use_blueprint:
    path: zha-ikea-tradfri-on-off.yaml
    input:
      remote: 6d28d5667edb2b868eff70fd11bd482a
      button_on_short:
      - service: light.toggle
        data:
          effect: Colortwinkles
          brightness_pct: 50
        target:
          entity_id: light.sk_elyza
      button_off_short:
      - type: toggle
        device_id: 02cacf930f07812e59e570f82c5ca227
        entity_id: light.slaapkamer
        domain: light
      button_on_long:
      - type: toggle
        device_id: 5ef0c84be1879822e4d1f39924f41cd7
        entity_id: light.wled_elyza
        domain: light
      button_off_long:
      - service: light.toggle
        target:
          entity_id: light.zolder
- id: '1630829375213'
  alias: Schakelaar - Rolgordijn
  description: ''
  use_blueprint:
    path: r3mcos3/ikea_open_close_remote.yaml
    input:
      remote: cc66f011e492b866cfffda5d7ff4856d
      cover: cover.rolgordijn
- id: '1630829568152'
  alias: Licht - WC
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: c68f9d21be09a8a9d631b4025f334626
    entity_id: binary_sensor.wc_motion
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 53087e3390780a0440609dd187364e13
    entity_id: switch.wc_licht
    domain: switch
  - wait_for_trigger:
    - type: no_motion
      platform: device
      device_id: c68f9d21be09a8a9d631b4025f334626
      entity_id: binary_sensor.wc_motion
      domain: binary_sensor
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 53087e3390780a0440609dd187364e13
    entity_id: switch.wc_licht
    domain: switch
  mode: restart
- id: '1630829664497'
  alias: Licht - Kelder
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 998ef6ac47b2081cefd9d2cff191775c
    entity_id: binary_sensor.kelder_motion
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 583255008fa6e3c33abaffc0d5da340e
    entity_id: light.kelder
    domain: light
    brightness_pct: 100
  - wait_for_trigger:
    - type: no_motion
      platform: device
      device_id: 998ef6ac47b2081cefd9d2cff191775c
      entity_id: binary_sensor.kelder_motion
      domain: binary_sensor
  - type: turn_off
    device_id: 583255008fa6e3c33abaffc0d5da340e
    entity_id: light.kelder
    domain: light
  mode: restart
- id: '1630829755710'
  alias: Volume Control
  description: ''
  use_blueprint:
    path: r3mcos3/volume_control.yaml
    input:
      media:
        device_id:
        - d64b69ecb57f7ae66498fb29641b6ebb
        - e2243ddf2291037173a4f27bcbebcbed
        - 80b17e38171741676fb6ed112a0210dc
        - a65c880d276523becfe34f1f44b8b000
        - fd25f3b4bdb670d909c81cda743a8a1d
      time_up: 08:30:00
      time_down: '20:00:00'
- id: '1630829880953'
  alias: Licht - Prullebak
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 6a2d4d761d32c8de40c687e01ecbde50
    entity_id: binary_sensor.achterdeur
    domain: binary_sensor
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - service: light.turn_on
    target:
      device_id:
      - 7682b2c0cd0b824545f3ae8011a7ee71
      - fa730a519480da09b832e94d3c8d4123
  - delay:
      hours: 0
      minutes: 1
      seconds: 30
      milliseconds: 0
  - service: light.turn_off
    target:
      device_id:
      - 7682b2c0cd0b824545f3ae8011a7ee71
      - fa730a519480da09b832e94d3c8d4123
  mode: restart
- id: '1630829982331'
  alias: Licht - Schuur
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: dc78b6723f3afd48e7f99ad45ff3b3d2
    entity_id: binary_sensor.schuur_motion_98d7b1fe_on_off
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_on
    target:
      device_id:
      - b846ef2bb4701180bacd419e1c49c985
      - df2e78bfb18d16f92f23a487b31518a9
      - 681c2133fc1dcec1c7bc8ab0b823a9df
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      device_id:
      - b846ef2bb4701180bacd419e1c49c985
      - df2e78bfb18d16f92f23a487b31518a9
      - 681c2133fc1dcec1c7bc8ab0b823a9df
  mode: restart
- id: '1630830182142'
  alias: Huis Status - Bewoond
  description: ''
  trigger:
  - platform: state
    entity_id: person.annemarie
    to: home
  - platform: state
    entity_id: person.dev
    to: home
  - platform: state
    entity_id: input_boolean.gasten_status
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.huis_status
  mode: single
- id: '1630830408962'
  alias: Huis Status - Onbewoond
  description: ''
  trigger:
  - platform: zone
    entity_id: person.annemarie
    zone: zone.home
    event: leave
  - platform: zone
    entity_id: person.dev
    zone: zone.home
    event: leave
  - platform: state
    entity_id: input_boolean.gasten_status
    to: 'off'
  condition:
  - condition: state
    entity_id: person.annemarie
    state: not_home
  - condition: state
    entity_id: person.dev
    state: not_home
  - condition: state
    entity_id: input_boolean.gasten_status
    state: 'off'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.huis_status
  mode: single
- id: '1630830595725'
  alias: Schakelaar - Keuken
  description: ''
  trigger:
  - platform: device
    domain: tasmota
    device_id: a2e725aed04f97b7eb8f3eadacd09782
    type: button_long_press
    subtype: button_1
    discovery_id: D8F15BE77D0A_button_1_HOLD
    id: long
  - platform: device
    domain: tasmota
    device_id: a2e725aed04f97b7eb8f3eadacd09782
    type: button_double_press
    subtype: button_1
    discovery_id: D8F15BE77D0A_button_1_DOUBLE
    id: double
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: long
      sequence:
      - service: light.toggle
        target:
          entity_id:
          - light.tuin_led
          - light.groot_licht
    - conditions:
      - condition: trigger
        id: double
      sequence:
      - service: light.toggle
        target:
          entity_id: light.patio
        data:
          brightness_pct: 50
    default: []
  mode: single
- id: '1630831176049'
  alias: Systeem - Update Beschikbaar
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.update_available
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_in2023
    data:
      title: 'HA Update Beschikbaar '
      message: Nieuwe versie is {{ states('sensor.newest_dev_version') }}. momenteel
        zit je op {{ states('sensor.installed_version') }}
  mode: single
- id: '1630831551618'
  alias: Schakelaar - Santi
  description: ''
  trigger:
  - platform: device
    domain: tasmota
    device_id: 8740fcd2b902c3c8fe7ab26e995ed5d9
    type: button_long_press
    subtype: button_1
    discovery_id: 2CF432C02815_button_1_HOLD
    id: hold
  - platform: device
    domain: tasmota
    device_id: 8740fcd2b902c3c8fe7ab26e995ed5d9
    type: button_double_press
    subtype: button_1
    discovery_id: 2CF432C02815_button_1_DOUBLE
    id: double
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: hold
      sequence:
      - type: toggle
        device_id: 6eeca783b2d9cfbbe21886b0993260eb
        entity_id: light.wled_santi
        domain: light
      - type: toggle
        device_id: 6eeca783b2d9cfbbe21886b0993260eb
        entity_id: switch.wled_santi_nightlight
        domain: switch
    - conditions:
      - condition: trigger
        id: double
      sequence:
      - service: cover.toggle
        target:
          device_id: 6e9ba0e145793df25490992ba89ce0e7
    default: []
  mode: single
- id: '1630836252141'
  alias: Licht - Thuis Komen
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 4638c662bc11fa913f1250cdae4aa3a3
    entity_id: binary_sensor.voordeur
    domain: binary_sensor
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  - condition: state
    entity_id: light.kast
    state: 'off'
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.kast
      - light.gang
      - light.keuken_spotjes
      - light.woonkamer_spotjes
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id: light.gang
  mode: single
- id: '1630837076353'
  alias: Alarm - Aan
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.huis_status
    to: 'off'
  condition: []
  action:
  - service: alarmo.arm
    data:
      entity_id: alarm_control_panel.alarmo
      code: '2012'
  mode: single
- id: '1630865815987'
  alias: Licht - Wekker Licht
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.next_alarm
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.kast
      - light.keuken_spotjes
  mode: single
