binary_sensor.raam_badkamer:
  device_class: window
binary_sensor.raam_elyza:
  device_class: window
binary_sensor.raam_slaapkamer:
  device_class: window
binary_sensor.raam_slaapkamer_santi:
  device_class: window
cover.rolluik_achter:
  device_class: shutter
cover.rolluik_boven:
  device_class: shutter
cover.rolluik_voor:
  device_class: shutter
binary_sensor.deur_keuken:
  device_class: door
binary_sensor.voor_deur:
  device_class: door
sensor.unraid_cpu_temp:
  unit_of_measurement: °C
  device_class: temperature
sensor.power_consumption:
  state_class: measurement
sensor.house_usage:
  last_reset: '"1970-01-01T00:00:00+00:00"'
