binary_sensor.raam_badkamer:
  device_class: window
binary_sensor.raam_elyza:
  device_class: window
binary_sensor.raam_slaapkamer:
  device_class: window
binary_sensor.raam_slaapkamer_santi:
  device_class: window
cover.rolluik_achter:
  device_class: shutter
cover.rolluik_boven:
  device_class: shutter
cover.rolluik_voor:
  device_class: shutter
binary_sensor.deur_keuken:
  device_class: door
binary_sensor.voor_deur:
  device_class: door
sensor.unraid_cpu_temp:
  unit_of_measurement: °C
  device_class: temperature
sensor.power_consumption:
  state_class: measurement
sensor.house_usage: {}
sensor.wasmachine_energy_total: {}
sensor.vaatwasser_energy:
  state_class: total_increasing
sensor.koelkast_keuken_energy:
  state_class: total_increasing
sensor.energy_consumption_tarif_1:
  last_reset: '1970-01-01T00:00:00.000Z'
  state_class: total_increasing
sensor.energy_consumption_tarif_2:
  last_reset: '1970-01-01T00:00:00.000Z'
  state_class: total_increasing
sensor.uurlijks_verbruik_dal:
  state_class: total_increasing
sensor.uurlijks_verbruik_normaal:
  state_class: total_increasing
sensor.dagelijks_verbruik_dal:
  state_class: total_increasing
sensor.dagelijks_verbruik_normaal:
  state_class: total_increasing
binary_sensor.badkamer_raam_contact:
  device_class: window
binary_sensor.sk_elyza_raam_contact:
  device_class: window
binary_sensor.sk_santi_raam_contact:
  device_class: window
binary_sensor.slaapkamer_raam_contact:
  device_class: window
sensor.koelkast_dagelijks:
  state_class: total_increasing
  unit_of_measurement: kWh
sensor.tz3000_g5xawfcq_ts0121_2730fffe_smartenergy_metering:
  state_class: total_increasing
binary_sensor.badkamer_raam:
  device_class: window
binary_sensor.sk_raam_elyza:
  device_class: window
binary_sensor.sk_raam_santi:
  device_class: window
binary_sensor.sk_raam:
  device_class: window
binary_sensor.voordeur:
  device_class: door
binary_sensor.achterdeur:
  device_class: door
